[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]
edition = "2021"

[dependencies]
itertools = "0.13"
bit-vec = "0.8"
clap = {version = "4.5", features = ["derive"]}