[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
