[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]
edition = "2021"

[dependencies]
itertools = "0.10"
bit-vec = "0.6"
clap = {version = "4.0", features = ["derive"]}