[package]
name = "advent-of-code-2023"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]
edition = "2021"

[dependencies]
advent-of-code-core = { path = "../core" }
more-asserts = "0.3"